### ISSUE TITLE
Exception Python 3.7 Django 2.2.4

### ISSUE THREAD

**Issue by Bastilla123** [arneb/django-messages#131]
I open URL:

http://127.0.0.1:8000/messages/compose/Sebastian/

then python throws:

Internal Server Error: /messages/compose/Sebastian/
Traceback (most recent call last):
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django_messages/views.py", line 94, in compose
    'form': form,
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/template/base.py", line 993, in render
    return render_value_in_context(output, context)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/template/base.py", line 972, in render_value_in_context
    value = str(value)
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/forms/forms.py", line 142, in __str__
    return self.as_table()
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/forms/forms.py", line 284, in as_table
    errors_on_separate_row=False,
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/forms/forms.py", line 243, in _html_output
    'field_name': bf.html_name,
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/home/sebastian/PycharmProjects/easydating/env/env/myvenv/lib/python3.7/site-packages/django/forms/boundfield.py", line 93, in as_widget
    renderer=self.form.renderer,
TypeError: render() got an unexpected keyword argument 'renderer'
"GET /messages/compose/Sebastian/ HTTP/1.1" 500 198416

**Comment by arneb** [comment]
can you please test with current master branch? This error was supposedly fixed yesterday, but no new release uploaded to pypi ...

**Comment by Bastilla123** [comment]
Yeah nice it works. Thanks

Am Mo., 12. Aug. 2019 um 18:41 Uhr schrieb Arne Brodowski <
notifications@github.com>:

**Comment by arneb** [comment]
thank you for the feedback. A new release will be made available shortly.

**Comment by Bastilla123** [comment]
Can you Tell me how i can User i18n with 'de-de'?

Arne Brodowski <notifications@github.com> schrieb am Di., 13. Aug. 2019,
09:48:

**Comment by arneb** [comment]
https://docs.djangoproject.com/en/2.2/topics/i18n/translation/#how-django-discovers-language-preference

settings.py:
```
USE_I18N = True
LANGUAGE_CODE = "de-de"
MIDDLEWARE = [
  #... 
   'django.contrib.sessions.middleware.SessionMiddleware',
   'django.middleware.locale.LocaleMiddleware',  # <-- this is important
   'django.middleware.common.CommonMiddleware',
  #... 
]
```

**Comment by Bastilla123** [comment]
Hello,

i have all this in my settings.py:

MIDDLEWARE = [
    #'simple_history.middleware.HistoryRequestMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
]

USE_I18N = True

LANGUAGE_CODE = 'de-de'

but when i write i message all labels from template where in english language.

Regards


Am Di., 13. Aug. 2019 um 11:10 Uhr schrieb Arne Brodowski <
notifications@github.com>:

**Comment by arneb** [comment]
try to remove all supported languages except german:

settings.LANGUAGES = [
  ('de', 'German'),
]

**Comment by Bastilla123** [comment]
Thank you IT works. Absolut amazing. Thanks

Arne Brodowski <notifications@github.com> schrieb am Di., 13. Aug. 2019,
11:45:
