### ISSUE TITLE
django_messages/management.py", line 1, in <module>     from django.db.models import get_models, signals ImportError: cannot import name get_models

### ISSUE THREAD

**Issue by jayliew** [arneb/django-messages#65]
django.db.models.get_model is deprecated from Django 1.9. It also doesn't look like get_models is used anywhere in django_messages/management.py

Can this import be removed safely?

```python
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/dude/.virtualenvs/foo/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/Users/dude/.virtualenvs/foo/lib/python2.7/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/dude/.virtualenvs/foo/lib/python2.7/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/Users/dude/.virtualenvs/foo/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/dude/.virtualenvs/foo/lib/python2.7/site-packages/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/Users/dude/.virtualenvs/foo/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/dude/.virtualenvs/foo/lib/python2.7/site-packages/django/core/management/commands/test.py", line 90, in handle
    failures = test_runner.run_tests(test_labels)
  File "/Users/dude/.virtualenvs/foo/lib/python2.7/site-packages/django/test/runner.py", line 532, in run_tests
    old_config = self.setup_databases()
  File "/Users/dude/.virtualenvs/foo/lib/python2.7/site-packages/django/test/runner.py", line 482, in setup_databases
    self.parallel, **kwargs
  File "/Users/dude/.virtualenvs/foo/lib/python2.7/site-packages/django/test/runner.py", line 726, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "/Users/dude/.virtualenvs/foo/lib/python2.7/site-packages/django/db/backends/base/creation.py", line 70, in create_test_db
    run_syncdb=True,
  File "/Users/dude/.virtualenvs/foo/lib/python2.7/site-packages/django/core/management/__init__.py", line 119, in call_command
    return command.execute(*args, **defaults)
  File "/Users/dude/.virtualenvs/foo/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/dude/.virtualenvs/foo/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 62, in handle
    import_module('.management', app_config.name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/dude/.virtualenvs/foo/lib/python2.7/site-packages/django_messages/management.py", line 1, in <module>
    from django.db.models import get_models, signals
ImportError: cannot import name get_models
```

**Comment by arneb** [comment]
thank you. I've merged your PR.
