### ISSUE TITLE
Django 1.10.5 ImportError: cannot import name patterns

### ISSUE THREAD

**Issue by MMoresi** [arneb/django-messages#91]
Hi, i've an issue, i've installed django-messages in Version
 >>> django_messages.VERSION
(0, 5, 3)

via pip install, im using python 2.7 and i got this error

```

mrc@mrc-desktop:~/Work/traego$ python manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7f385efbe410>
Traceback (most recent call last):
  File "/home/mrc/.virtualenvs/traego/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/mrc/.virtualenvs/traego/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/home/mrc/.virtualenvs/traego/local/lib/python2.7/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/mrc/.virtualenvs/traego/local/lib/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/mrc/.virtualenvs/traego/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/mrc/.virtualenvs/traego/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/mrc/.virtualenvs/traego/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/mrc/.virtualenvs/traego/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/mrc/.virtualenvs/traego/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/mrc/.virtualenvs/traego/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/mrc/.virtualenvs/traego/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/mrc/Work/traego/traego/urls.py", line 83, in <module>
    url(r'^messages/', include('django_messages.urls')),
  File "/home/mrc/.virtualenvs/traego/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/mrc/.virtualenvs/traego/local/lib/python2.7/site-packages/django_messages/urls.py", line 1, in <module>
    from django.conf.urls import patterns, url
ImportError: cannot import name patterns
```

should i install the lastet version? how do it do it? can do i via pip or i have to do it manually?
thanks

**Comment by arneb** [comment]
use the lastes version from github:

    pip install git+https://github.com/arneb/django-messages.git@master

**Comment by MMoresi** [comment]
By this way it install an old version again, am i doing anything wrong?

`(test2) mrc@mrc-desktop:~$ pip install git+https://github.com/arneb/django-messages.git@master 
Collecting git+https://github.com/arneb/django-messages.git@master
  Cloning https://github.com/arneb/django-messages.git (to master) to /tmp/pip-u_rm4zhl-build
Collecting Django (from django-messages==0.5.3)
  Using cached Django-1.11-py2.py3-none-any.whl
Collecting pytz (from Django->django-messages==0.5.3)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Installing collected packages: pytz, Django, django-messages
  Running setup.py install for django-messages ... done
Successfully installed Django-1.11 django-messages-0.5.3 pytz-2017.2
`

**Comment by arneb** [comment]
The current version number ist 0.5.3
https://github.com/arneb/django-messages/blob/master/django_messages/__init__.py
It will increase, when the next release is finishes.
